<?php

declare(strict_types = 1);

namespace OpenSearch\Endpoints\Notifications;

use OpenSearch\Endpoints\AbstractEndpoint;

/**
 * Class DeleteConfigs
 * NOTE: this file is autogenerated using util/GenerateEndpoints.php
 * and OpenSearch :version (:buildhash)
 */
class DeleteConfigs extends AbstractEndpoint
{

    public function getURI(): string
    {

        return "/_plugins/_notifications/configs";
    }

    public function getParamWhitelist(): array
    {
        return [
            'config_id',
            'config_id_list',
            'pretty',
            'human',
            'error_trace',
            'source',
            'filter_path'
        ];
    }

    public function getMethod(): string
    {
        return 'DELETE';
    }
}
