<?php

declare(strict_types = 1);

namespace OpenSearch\Endpoints\SearchPipeline;

use OpenSearch\Common\Exceptions\RuntimeException;
use OpenSearch\Endpoints\AbstractEndpoint;

/**
 * Class Delete
 * NOTE: this file is autogenerated using util/GenerateEndpoints.php
 * and OpenSearch :version (:buildhash)
 */
class Delete extends AbstractEndpoint
{

    public function getURI(): string
    {
        $id = $this->id ?? null;

        if (isset($id)) {
            return "/_search/pipeline/$id";
        }
        throw new RuntimeException('Missing parameter for the endpoint search_pipeline.delete');
    }

    public function getParamWhitelist(): array
    {
        return [
            'cluster_manager_timeout',
            'timeout',
            'pretty',
            'human',
            'error_trace',
            'source',
            'filter_path'
        ];
    }

    public function getMethod(): string
    {
        return 'DELETE';
    }
}
