<?php

declare(strict_types = 1);

namespace OpenSearch\Endpoints\Cluster;

use OpenSearch\Common\Exceptions\RuntimeException;
use OpenSearch\Endpoints\AbstractEndpoint;

/**
 * Class GetDecommissionAwareness
 * NOTE: this file is autogenerated using util/GenerateEndpoints.php
 * and OpenSearch :version (:buildhash)
 */
class GetDecommissionAwareness extends AbstractEndpoint
{
    protected $awareness_attribute_name;

    public function getURI(): string
    {
        $awareness_attribute_name = $this->awareness_attribute_name ?? null;

        if (isset($awareness_attribute_name)) {
            return "/_cluster/decommission/awareness/$awareness_attribute_name/_status";
        }
        throw new RuntimeException('Missing parameter for the endpoint cluster.get_decommission_awareness');
    }

    public function getParamWhitelist(): array
    {
        return [
            'pretty',
            'human',
            'error_trace',
            'source',
            'filter_path'
        ];
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function setAwarenessAttributeName($awareness_attribute_name): GetDecommissionAwareness
    {
        if (isset($awareness_attribute_name) !== true) {
            return $this;
        }
        $this->awareness_attribute_name = $awareness_attribute_name;

        return $this;
    }
}
