<?php

declare(strict_types = 1);

namespace OpenSearch\Endpoints\Cluster;

use OpenSearch\Common\Exceptions\RuntimeException;
use OpenSearch\Endpoints\AbstractEndpoint;

/**
 * Class PutWeightedRouting
 * NOTE: this file is autogenerated using util/GenerateEndpoints.php
 * and OpenSearch :version (:buildhash)
 */
class PutWeightedRouting extends AbstractEndpoint
{
    protected $attribute;

    public function getURI(): string
    {
        $attribute = $this->attribute ?? null;

        if (isset($attribute)) {
            return "/_cluster/routing/awareness/$attribute/weights";
        }
        throw new RuntimeException('Missing parameter for the endpoint cluster.put_weighted_routing');
    }

    public function getParamWhitelist(): array
    {
        return [
            'pretty',
            'human',
            'error_trace',
            'source',
            'filter_path'
        ];
    }

    public function getMethod(): string
    {
        return 'PUT';
    }

    public function setAttribute($attribute): PutWeightedRouting
    {
        if (isset($attribute) !== true) {
            return $this;
        }
        $this->attribute = $attribute;

        return $this;
    }
}
