<?php

declare(strict_types = 1);

namespace OpenSearch\Endpoints\Security;

use OpenSearch\Common\Exceptions\RuntimeException;
use OpenSearch\Endpoints\AbstractEndpoint;

/**
 * Class CreateActionGroup
 * NOTE: this file is autogenerated using util/GenerateEndpoints.php
 * and OpenSearch :version (:buildhash)
 */
class CreateActionGroup extends AbstractEndpoint
{
    protected $action_group;

    public function getURI(): string
    {
        if (isset($this->action_group) !== true) {
            throw new RuntimeException(
                'action_group is required for create_action_group'
            );
        }
        $action_group = $this->action_group;

        return "/_plugins/_security/api/actiongroups/$action_group";
    }

    public function getParamWhitelist(): array
    {
        return [
            'pretty',
            'human',
            'error_trace',
            'source',
            'filter_path'
        ];
    }

    public function getMethod(): string
    {
        return 'PUT';
    }

    public function setBody($body): CreateActionGroup
    {
        if (isset($body) !== true) {
            return $this;
        }
        $this->body = $body;

        return $this;
    }

    public function setActionGroup($action_group): CreateActionGroup
    {
        if (isset($action_group) !== true) {
            return $this;
        }
        $this->action_group = $action_group;

        return $this;
    }
}
