<?php

declare(strict_types = 1);

namespace OpenSearch\Endpoints\Security;

use OpenSearch\Common\Exceptions\RuntimeException;
use OpenSearch\Endpoints\AbstractEndpoint;

/**
 * Class DeleteRoleMapping
 * NOTE: this file is autogenerated using util/GenerateEndpoints.php
 * and OpenSearch :version (:buildhash)
 */
class DeleteRoleMapping extends AbstractEndpoint
{
    protected $role;

    public function getURI(): string
    {
        if (isset($this->role) !== true) {
            throw new RuntimeException(
                'role is required for delete_role_mapping'
            );
        }
        $role = $this->role;

        return "/_plugins/_security/api/rolesmapping/$role";
    }

    public function getParamWhitelist(): array
    {
        return [
            'pretty',
            'human',
            'error_trace',
            'source',
            'filter_path'
        ];
    }

    public function getMethod(): string
    {
        return 'DELETE';
    }

    public function setRole($role): DeleteRoleMapping
    {
        if (isset($role) !== true) {
            return $this;
        }
        $this->role = $role;

        return $this;
    }
}
