<?php

declare(strict_types = 1);

namespace OpenSearch\Endpoints\Security;

use OpenSearch\Endpoints\AbstractEndpoint;

/**
 * Class GetDistinguishedNames
 * NOTE: this file is autogenerated using util/GenerateEndpoints.php
 * and OpenSearch :version (:buildhash)
 */
class GetDistinguishedNames extends AbstractEndpoint
{
    protected $cluster_name;

    public function getURI(): string
    {
        $cluster_name = $this->cluster_name ?? null;

        if (isset($cluster_name)) {
            return "/_plugins/_security/api/nodesdn/$cluster_name";
        }
        return "/_plugins/_security/api/nodesdn";
    }

    public function getParamWhitelist(): array
    {
        return [
            'pretty',
            'human',
            'error_trace',
            'source',
            'filter_path'
        ];
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function setClusterName($cluster_name): GetDistinguishedNames
    {
        if (isset($cluster_name) !== true) {
            return $this;
        }
        $this->cluster_name = $cluster_name;

        return $this;
    }
}
