<?php

declare(strict_types = 1);

namespace OpenSearch\Endpoints\Security;

use OpenSearch\Common\Exceptions\RuntimeException;
use OpenSearch\Endpoints\AbstractEndpoint;

/**
 * Class UpdateDistinguishedNames
 * NOTE: this file is autogenerated using util/GenerateEndpoints.php
 * and OpenSearch :version (:buildhash)
 */
class UpdateDistinguishedNames extends AbstractEndpoint
{
    protected $cluster_name;

    public function getURI(): string
    {
        $cluster_name = $this->cluster_name ?? null;

        if (isset($cluster_name)) {
            return "/_plugins/_security/api/nodesdn/$cluster_name";
        }
        throw new RuntimeException('Missing parameter for the endpoint security.update_distinguished_names');
    }

    public function getParamWhitelist(): array
    {
        return [
            'pretty',
            'human',
            'error_trace',
            'source',
            'filter_path'
        ];
    }

    public function getMethod(): string
    {
        return 'PUT';
    }

    public function setBody($body): UpdateDistinguishedNames
    {
        if (isset($body) !== true) {
            return $this;
        }
        $this->body = $body;

        return $this;
    }

    public function setClusterName($cluster_name): UpdateDistinguishedNames
    {
        if (isset($cluster_name) !== true) {
            return $this;
        }
        $this->cluster_name = $cluster_name;

        return $this;
    }
}
